services:
  homepage-tailscale:
    image: tailscale/tailscale:latest
    container_name: homepage-tailscale
    hostname: homepage
    healthcheck:
      test: ["CMD", "tailscale", "status", "--peers=false"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=homepage.json
      - TS_ACCEPT_DNS=true
      - TS_EXTRA_ARGS=--reset
    volumes:
      - homepage-tailscale:/var/lib/tailscale
      - /lib/modules:/lib/modules:ro
      - ./homepage.json:/homepage.json
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    network_mode: service:homepage-tailscale
    environment:
      HOMEPAGE_VAR_PIHOLE_PASSWORD: ${HOMEPAGE_VAR_PIHOLE_PASSWORD}

      HOMEPAGE_VAR_OMADA_USERNAME: ${HOMEPAGE_VAR_OMADA_USERNAME}
      HOMEPAGE_VAR_OMADA_PASSWORD: ${HOMEPAGE_VAR_OMADA_PASSWORD}
      HOMEPAGE_VAR_OMADA_SITE: ${HOMEPAGE_VAR_OMADA_SITE}

      HOMEPAGE_VAR_TAILSCALE_ID_INTRANET: ${HOMEPAGE_VAR_TAILSCALE_ID_INTRANET}
      HOMEPAGE_VAR_TAILSCALE_ID_MACBOOK: ${HOMEPAGE_VAR_TAILSCALE_ID_MACBOOK}
      HOMEPAGE_VAR_TAILSCALE_ID_PHONE: ${HOMEPAGE_VAR_TAILSCALE_ID_PHONE}
      HOMEPAGE_VAR_TAILSCALE_KEY: ${HOMEPAGE_VAR_TAILSCALE_KEY}
    volumes:
      - ./config:/app/config
    depends_on:
      homepage-tailscale:
        condition: service_healthy
    restart: unless-stopped

volumes:
  homepage-tailscale:
