services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - home-intranet-nginx
    environment:
      VIRTUAL_HOST: "www.intranet.local"
      VIRTUAL_PROTO: "http"
      VIRTUAL_PORT: 3000

      HOMEPAGE_VAR_PIHOLE_PASSWORD: ${HOMEPAGE_VAR_PIHOLE_PASSWORD}

      HOMEPAGE_VAR_OMADA_USERNAME: ${HOMEPAGE_VAR_OMADA_USERNAME}
      HOMEPAGE_VAR_OMADA_PASSWORD: ${HOMEPAGE_VAR_OMADA_PASSWORD}
      HOMEPAGE_VAR_OMADA_SITE: ${HOMEPAGE_VAR_OMADA_SITE}

      HOMEPAGE_VAR_TAILSCALE_ID_INTRANET: ${HOMEPAGE_VAR_TAILSCALE_ID_INTRANET}
      HOMEPAGE_VAR_TAILSCALE_ID_MACBOOK: ${HOMEPAGE_VAR_TAILSCALE_ID_MACBOOK}
      HOMEPAGE_VAR_TAILSCALE_ID_PHONE: ${HOMEPAGE_VAR_TAILSCALE_ID_PHONE}
      HOMEPAGE_VAR_TAILSCALE_KEY: ${HOMEPAGE_VAR_TAILSCALE_KEY}
    dns:
      - 172.20.0.100
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  home-intranet-nginx:
    external: true
