services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: home-intranet-homepage
    ports:
      - "3001:3000"
    environment:
      HOMEPAGE_VAR_PIHOLE_API_TOKEN: ${HOMEPAGE_VAR_PIHOLE_API_TOKEN}
      HOMEPAGE_VAR_OMADA_USERNAME: ${HOMEPAGE_VAR_OMADA_USERNAME}
      HOMEPAGE_VAR_OMADA_PASSWORD: ${HOMEPAGE_VAR_OMADA_PASSWORD}
      HOMEPAGE_VAR_OMADA_SITE: ${HOMEPAGE_VAR_OMADA_SITE}
      HOMEPAGE_VAR_TAILSCALE_ID_INTRANET: ${HOMEPAGE_VAR_TAILSCALE_ID_INTRANET}
      HOMEPAGE_VAR_TAILSCALE_ID_MACBOOK: ${HOMEPAGE_VAR_TAILSCALE_ID_MACBOOK}
      HOMEPAGE_VAR_TAILSCALE_ID_PHONE: ${HOMEPAGE_VAR_TAILSCALE_ID_PHONE}
      HOMEPAGE_VAR_TAILSCALE_KEY: ${HOMEPAGE_VAR_TAILSCALE_KEY}
    dns:
      - 192.168.0.39
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
