services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: home-intranet-homepage
    environment:
      HOMEPAGE_VAR_STIRLING_URL: ${HOMEPAGE_VAR_STIRLING_URL}

      HOMEPAGE_VAR_PIHOLE_URL: ${HOMEPAGE_VAR_PIHOLE_URL}
      HOMEPAGE_VAR_PIHOLE_ADMIN_PANEL: ${HOMEPAGE_VAR_PIHOLE_ADMIN_PANEL}
      HOMEPAGE_VAR_PIHOLE_PASSWORD: ${HOMEPAGE_VAR_PIHOLE_PASSWORD}

      HOMEPAGE_VAR_OMADA_USERNAME: ${HOMEPAGE_VAR_OMADA_USERNAME}
      HOMEPAGE_VAR_OMADA_PASSWORD: ${HOMEPAGE_VAR_OMADA_PASSWORD}
      HOMEPAGE_VAR_OMADA_SITE: ${HOMEPAGE_VAR_OMADA_SITE}

      HOMEPAGE_VAR_TAILSCALE_ID_INTRANET: ${HOMEPAGE_VAR_TAILSCALE_ID_INTRANET}
      HOMEPAGE_VAR_TAILSCALE_ID_MACBOOK: ${HOMEPAGE_VAR_TAILSCALE_ID_MACBOOK}
      HOMEPAGE_VAR_TAILSCALE_ID_PHONE: ${HOMEPAGE_VAR_TAILSCALE_ID_PHONE}
      HOMEPAGE_VAR_TAILSCALE_KEY: ${HOMEPAGE_VAR_TAILSCALE_KEY}

      HOMEPAGE_VAR_GITHUB_URL: ${HOMEPAGE_VAR_GITHUB_URL}

      HOMEPAGE_VAR_JENKINS_URL: ${HOMEPAGE_VAR_JENKINS_URL}
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
