- Networking:
    - PiHole:
        id: pihole
        icon: si-pihole
        href: https://pihole.intranet.local
        widget:
            type: pihole
            url: https://pihole.intranet.local
            version: 6
            key: {{HOMEPAGE_VAR_PIHOLE_PASSWORD}}
    - Omada:
        id: omada
        icon: si-omadacloud
        href: https://omada.intranet.local
        widget:
            type: omada
            url: https://omada.intranet.local
            username: {{HOMEPAGE_VAR_OMADA_USERNAME}}
            password: {{HOMEPAGE_VAR_OMADA_PASSWORD}}
            site: {{HOMEPAGE_VAR_OMADA_SITE}}
    - Tailscale:
        id: tailscale
        icon: si-tailscale
        href: https://login.tailscale.com
        widgets:
            - type: tailscale
              deviceid: {{HOMEPAGE_VAR_TAILSCALE_ID_INTRANET}}
              key: {{HOMEPAGE_VAR_TAILSCALE_KEY}}
            - type: tailscale
              deviceid: {{HOMEPAGE_VAR_TAILSCALE_ID_MACBOOK}}
              key: {{HOMEPAGE_VAR_TAILSCALE_KEY}}
            - type: tailscale
              deviceid: {{HOMEPAGE_VAR_TAILSCALE_ID_PHONE}}
              key: {{HOMEPAGE_VAR_TAILSCALE_KEY}}

- Developer Tools:
    - Github:
        id: github
        icon: si-github
        href: https://github.com/Lanham-Software-James?tab=repositories
    - Jenkins:
        id: jenkins
        icon: si-jenkins
        href: https://jenkins.intranet.local/

- Local Resources:
    - Printer:
        id: printer
        icon: si-hp
        href: https://192.168.0.34/
