# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Networking:
    - PiHole:
        id: 100
        icon: pi-hole.png
        href: https://pihole.intranet.local
        widget:
            type: pihole
            url: https://pihole.intranet.local
            version: 5
            key:  {{HOMEPAGE_VAR_PIHOLE_API_TOKEN}}
    - Omada:
        id: 200
        icon: omada.png
        href: https://omada.intranet.local
        widget:
            type: omada
            url: https://omada.intranet.local
            username: {{HOMEPAGE_VAR_OMADA_USERNAME}}
            password: {{HOMEPAGE_VAR_OMADA_PASSWORD}}
            site: {{HOMEPAGE_VAR_OMADA_SITE}}
    - Github:
        id: 300
        href: https://github.com/Lanham-Software-James?tab=repositories
    - Jenkins:
        id: 300
        href: https://jenkins.intranet.local/
