# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- Networking:
    - PiHole:
        id: 100
        icon: pi-hole.png
        href: https://pihole.homeintranet.local
        widget:
            type: pihole
            url: https://pihole.homeintranet.local
            version: 5
            key:  {{HOMEPAGE_VAR_PIHOLE_API_TOKEN}}

