# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

- Tools:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- Networking:
    - PiHole:
        id: 100
        icon: pi-hole.png
        href: https://pihole.homeintranet.local
        widget:
            type: pihole
            url: https://pihole.homeintranet.local
            version: 5
            key:  {{HOMEPAGE_VAR_PIHOLE_API_TOKEN}}
    - Omada:
        id: 200
        icon: omada.png
        href: https://omada.homeintranet.local
        widget:
            type: omada
            url: https://omada.homeintranet.local
            username: {{HOMEPAGE_VAR_OMADA_USERNAME}}
            password: {{HOMEPAGE_VAR_OMADA_PASSWORD}}
            site: {{HOMEPAGE_VAR_OMADA_SITE}}
