---
- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: true

- resources:
    label: "Home Intranet"
    cpu: true
    memory: true
    disk: /
    uptime: true
